server:
  host: "0.0.0.0"
  port: 8092

logging:
  level: "info"
  format: "text"

metrics:
  collection:
    default_interval: "30s"

printer:
  host: "192.168.1.100"
  community: "public"
  type: "laser"
