server:
  host: "0.0.0.0"
  port: 8080

logging:
  level: "info"
  format: "json"

metrics:
  collection:
    default_interval: "30s"

printer:
  host: "192.168.1.100"  # Replace with your Brother printer IP
  community: "public"    # SNMP community string
  type: "laser"          # "laser" or "ink"
